# Generated by Django 5.0.6 on 2025-01-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('user', 'User'), ('admin', 'Admin'), ('delivery_boy', 'Delivery Boy'), ('device_specialist', 'Device Specialist')], max_length=20),
        ),
    ]
