# Generated by Django 5.0.6 on 2025-01-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Order Confirmed', max_length=20),
        ),
    ]
