# Generated by Django 5.0.6 on 2025-01-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_payment_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
