# Generated by Django 5.0.6 on 2025-01-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_notification_is_read_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Out of Delivery', 'Out of Delivery')], default='Order Confirmed', max_length=20),
        ),
    ]
