# Generated by Django 5.0.6 on 2025-01-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_payment_otp_alter_payment_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
