# Generated by Django 5.0.6 on 2025-02-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_payment_latitude_payment_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldPhoneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'old_phone_category',
            },
        ),
    ]
