# Generated by Django 5.0.6 on 2025-02-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_oldphonecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldphonecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='old_phone_categories/'),
        ),
    ]
