# Generated by Django 5.0.6 on 2025-02-05 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_oldphonecategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldPhoneSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.oldphonecategory')),
            ],
            options={
                'db_table': 'old_phone_subcategory',
            },
        ),
    ]
