# Generated by Django 5.0.6 on 2025-02-06 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_oldphonesubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldPhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.oldphonesubcategory')),
            ],
        ),
    ]
