# Generated by Django 5.0.6 on 2025-02-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_oldphonemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('imei_number', models.CharField(max_length=15, unique=True)),
                ('phone_category', models.CharField(max_length=255)),
                ('phone_subcategory', models.CharField(max_length=255)),
                ('phone_model', models.CharField(max_length=255)),
                ('phone_condition', models.CharField(choices=[('Like New', 'Like New'), ('Good', 'Good'), ('Average', 'Average'), ('Needs Repair', 'Needs Repair')], max_length=50)),
                ('pickup_date', models.DateField()),
                ('pincode', models.CharField(max_length=10)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('pickup_address', models.TextField()),
                ('phone_images', models.FileField(blank=True, null=True, upload_to='phone_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
