# Generated by Django 5.0.6 on 2025-02-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_phonerepairrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonerepairrequest',
            name='expected_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
